### ISSUE TITLE
Insert the last node dynamics

### ISSUE THREAD

**Issue by ldd289806329** [mikafabricius/LumpedMassSpring_Umbilical_model#1]
Hello, I am very happy to see the code and simulation case you shared. It has been very helpful to me. But if I want to apply it to my project, I need to make some modifications to the code. I have two questions. If I want to apply a force or displacement at the last node, the magnitude and direction of this force are calculated by another MATLAB program at the same time step, which means that this force changes in real time. Should I modify your model in Simulink or MATLAB file. Additionally, in the MATLAB file ([To use the MATLAB model](url)), I would like to add a dynamic equation at the last node, but I am not sure what the form of this dynamic equation is? I hope and look forward to receiving some advice from you. Thank you very much.

**Comment by mikafabricius** [comment]
Hello, I'm happy to see that you have found my code useful.
I'm not sure I understand what you want to do, please feel free to try and explain it to me again.
But what I think you most likely want to do, is to add some sort of body at the last node that has its own dynamic equation. In this case you would take and initialize the last node as the position of that body. So the last node will be the body that you are modelling.
So when you run the cable model and the dynamic model of your body (At the same time), you use the cable model to model the forces from first node to last node, these forces are then applied in the dynamic model of your body as "disturbance forces" (Only the forces on the last node), on the right side of your first principle model (e.g. Newtons second law, m*a = F + disturbance). When calculating this equation from the body, you will get a position estimate. This position estimate is the position of the last node, so you will overwrite the position of the last node from the cable model, with the position from your dynamic equation for the body.
That is pretty much it, they should now be working together and you can do all kinds of fun simulations with it.
Remember to note that if the simulations crash due to large forces, the fixed timestep should be decreased. This occurs since the lms cable model is a stiff equation. Initializing the cable nodes with wrong distances, compared to your parameters in the cable model, can also be a cause of trouble.

You can also implement the model in Simulink of course, this is what i ended up doing, since I had my ROTV model in Simulink. I sadly do not have access to my license anymore, so I cant share it with you.

So in Simulink you would basically have the last node forces coming out of your cable model block and these would the go into the block with your dynamic equation for your body. Out from your body block your would then have the position of the body, which would then go into your cable model block, as the new position for the last node.

I hope this helps, otherwise feel free to ask again or clarify your question.
Best regards, Mika Fabricius

**Comment by ldd289806329** [comment]
Sorry, I didn't fully express my concerns before. If you are also interested, let me introduce my project again. A mooring cable is very long, with one end fixed on the ship and the other end fixed on the seabed. Currently, there is not a large enough pool for mooring tests. I need to cut off this mooring in the middle. One part is the ship and half mooring, and the other part is half mooring fixed on the seabed. The current problem is how to handle the motion of two parts at the truncation point, so that they approach the state before truncation. When doing simulation, my approach is to calculate the displacement of the last node of the upper mooring at the same time step and apply it to the first node of the lower mooring. At this point, the lower mooring will receive a feedback force, which will act on the last node of the upper mooring. This can complete the simulation. I don't know how to apply a displacement or force at the cutoff point (last node, first node). I hope to receive your guidance and look forward to your reply. Thank you very much！
![image](https://github.com/mikafabricius/lumped_mass_spring_cable_model/assets/111641893/c960405f-c6f4-4f74-bad1-e56b623e59f9)

**Comment by ldd289806329** [comment]
Can you tell me how to fix the last node in a certain position, or input the motion equation of the last node?

**Comment by mikafabricius** [comment]
Hello again, sorry for the late response, busy at work at the moment.

So if I understand correctly, you would like to apply to the last node of my model, based on your pictures as well, is the force from another model (or fixed position).

At line 86 in my code is where you would implement the last node dynamics, meaning external forces acting on the node.
In this case you are still using the "model" for the node, you just want to apply an additional force. So you would need to use is the dynamical equation that is also used in the Runge-Kutta mehod, this means function "f2".
Here you would add another force to the force balance in line 114, so it will be something like:
f2 = (buoyancy(r,d,g,l0,rho)-gravity(r,g,m)-drag(r,v,vc,Cn,Ct,d,rho)+tension_im1(r,d,E,l0)+tension_i(r,d,E,l0)-waves)/(M) + newforce;
This newforce when then have to be added in the main function call (cable_model_matlab(cableLength,segments,velocityShip,current,waves,ts,simulationTime,r_ini,v_ini,newforce)) and in all other function calls to the f2 function.
Just make sure that the newforce is the same length as the other variables and then have all entries set to 0, except for the last entries.
If you want to fix the last node in a certain position, by looking at the code, line 86, is where you would write the fixed position.
So what you will write at line 86 is:  r(k,:,i+1) = [x y z];
Make sure the the initialization position of the last node, matches with this node position.

Please return if none these works or if you have trouble implementing them.
